### ISSUE TITLE
Why the need for US English to be selected as well?

### ISSUE THREAD

**Issue by vphantom** [google/extra-keyboards-for-chrome-os#10]
Hello,

I'm about to fork composekey for my own use (to mimic actual Xorg sequences, maybe add a few I'd like, and to add availability for my Canadian French layout in addition to US English). Before I do so, I'd like to understand if a current limitation is insurmountable, to make sure I do things in the best way possible.

Right now, we must leave US English enabled, and additionally enable ComposeKey as keyboards, and somehow ComposeKey will do its work when selected (Alt-Shift) but not when US English is selected. I can't quite figure out how that works. I looked at the manifest and code and also couldn't see where the label "EN*" was defined.

This also means that if I duplicate this process for say 3 languages, now I'd have to cycle through 6 layouts in everyday use instead of the 3. (Ctrl-Space would help after each was used once in a session I assume, though.)

So I'm wondering, is keeping US English enabled absolutely necessary or could there be a way to stand alone?  Would standing alone involve only duplicating US English's "typing" keys or also (not sure how) all of ChromeOS' keyboard shortcuts?

Thank you for your time.

**Comment by bcmills** [comment]
As far as I can tell it's a limit of the `manifest.json` file format. It requires each entry in `input_components` to specify a language and layout, and when you switch input methods it automatically switches to the layout of that input method.

(So you end up needing to declare a separate input component for each supporting language × layout.)

There is also the not-so-small matter that we currently consume the Compose key on the `keydown` event: if you have your Compose key set to the same key as your AltGr key, it will likely no longer function as AltGr.

I have a change pending to address the latter issue. I'll let you know when I send the pull request.

**Comment by bcmills** [comment]
(I'm also planning to add general support for XCompose files, so that might address your “mimic actual Xorg sequences” use-case.)

**Comment by nathgit** [comment]
From the manifest file

"input_components": [
    {
      "name": "Compose Key (US)",
      "type": "ime",
      "id": "compose_key",
      "description": "Adds Compose key functionality to the US keyboard.",
      "language": "en-US",
      "layouts": ["us"]

couldn't you just duplicate the above code but change "en-US' and ["us"] to the relevant code?
something like this but setting it to Canadian French. (also from the manifest file)
{
      "name": "Compose Key (Canadian English)",
      "type": "ime",
      "id": "compose_key_ca_eng",
      "description": "Adds Compose key functionality to the US Workman keyboard.",
      "language": "en-CA",
      "layouts": ["ca(eng)"]
    }

**Comment by bderrly** [comment]
The composekey extension now has support for many US, CA, and GB layouts built into the manifest.
