### ISSUE TITLE
Second user account support

### ISSUE THREAD

**Issue by suniltheblue** [google/extra-keyboards-for-chrome-os#103]
I'm using a keyboard made with this code. It works perfect for the first user but I can't even add the keyboard to the second user account of the device. Is there a way to achieve this? Thanks a lot for your kind help.

**Comment by suniltheblue** [comment]
Hi @bderrly, could you please suggest some idea? Thanks a lot!

**Comment by bderrly** [comment]
I'm not sure what the problem is. I have multiple accounts logged into my Chromebook and they can all access the different layouts. I have the extension installed for each of the users. Perhaps that is the difference?

**Comment by suniltheblue** [comment]
Yes, I have installed the extension for the second user too. But when I try to add that input method, and press "Add" it does nothing. The same extension is working flawlessly for first user though. :(

Here is the screen preview:
https://user-images.githubusercontent.com/58907663/114599723-c558f880-9c93-11eb-9600-eceb1319cbf9.mp4

**Comment by hickford** [comment]
@suniltheblue try adding the Nepali language before adding the keyboard layout. See https://crbug.com/1190845

**Comment by suniltheblue** [comment]
@hickford your are my savior. Thank you so much! It worked!!! :)

**Comment by hickford** [comment]
You're welcome!

**Comment by bderrly** [comment]
Yes, you definitely need to have the language specified in the manifest added to the system before the layout will work.
