### ISSUE TITLE
How to get the Macintosh variant of the US keyboard?

### ISSUE THREAD

**Issue by RJVB** [google/extra-keyboards-for-chrome-os#108]
Linux has a US keyboard variant that's great for getting accented characters when you're used to using Macs. It uses the "3rd level" key (I use R_ALT for that) as a deadkey so you can then use R_ALT+e to get é, R_ALT+i to get î etc.

I see that `/usr/share/X11/xkb/symbols/us` includes this variant (under `xkb_symbols "mac"`) but I cannot find a way to activate it nor would I know how to (re)define the 3rd level key. I tried adding `export "XKB_DEFAULT_LAYOUT=us(mac)"` and `export XKB_DEFAULT_LAYOUT_OPTIONS=eurosign:4,grp:alts_toggle,lv3:ralt_switch` in `~chronos/.bashrc` but the only visible effect of that was that the keyboard layout indicator disappeared from the dock.

Any suggestions?

**Comment by hickford** [comment]
Hi. Have you tried layout "English (US) with International keyboard"? This gives ralt+e=é and ralt+i=í (NB. acute accent rather than circumflex).

![image](https://user-images.githubusercontent.com/105314/130626193-cf9e3282-fcf5-4356-8c67-bd0d91373af1.png)

There are charts for these layouts labelled 'chromeos' at https://unicode-org.github.io/cldr-staging/charts/latest/keyboards/layouts/en.html but some names have changed.

**Comment by hickford** [comment]
Another extension https://github.com/hickford/xkb-keyboard-layouts-for-chrome-os includes the basic us(mac) layout, but it's not possible to specify XKB options on top.

**Comment by RJVB** [comment]
>Another extension https://github.com/hickford/xkb-keyboard-layouts-for-chrome-os includes the basic us(mac) layout, but it's not possible to specify XKB options on top.

The "international" variant is not practical for me, it's both too different and too similar so I make constant errors. IIRC there's also one with the same name where `, ', ^ etc. are deadkeys themselves, which makes it unusable if you have the habit of using those characters yourself.

I'll see how the us(mac) layout works as provided by the extension, hopefully it is configured with the right 3rd level key, thanks.

**Comment by RJVB** [comment]
Turns out the `us(mac)` uses R_ALT by default (or it's because I set `XKB_DEFAULT_LAYOUT_OPTIONS` in my `~chronos/.bashrc`). Either way, thanks, and sorry for not having installed the extension before asking here!
