### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by cizmazia** [google/extra-keyboards-for-chrome-os#23]
Please could you explain how the extension/manifest file work from the security point of view? How can I assure that the extension is not capturing keystrokes? Thanks!

**Comment by bderrly** [comment]
You can review the javascript code in background.js to verify it isn't doing anything fishy. The manifest is used to define metadata for the extension. In particular these extensions are declaring the need for access to the Chrome input module (https://developer.chrome.com/extensions/input_ime) which allows the extension access to keyboard input.

**Comment by cizmazia** [comment]
I was interested specifically in the "slovakqwerty" extension. This one does not even seem to reference a script. How does it work? Thanks again!

**Comment by bderrly** [comment]
I see. Essentially the input module can take in a language and keyboard layout. They are the same values you would use for XkbLayout and XkbVariant (https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg#Setting_keyboard_layout). You'd need to look through the input code of chromium if you're feeling paranoid about key logging. The Slovak qwerty extension is not doing any local processing; it is only changing the keyboard layout used.

**Comment by cizmazia** [comment]
Thanks for clarifying! I asked because Chromebooks are popping up a security warning and thought it might be worth a note in the installations instructions.
