### ISSUE TITLE
Bullet doesn't work

### ISSUE THREAD

**Issue by AceOfThumbs** [google/extra-keyboards-for-chrome-os#32]
Most of the Compose Key shortcuts work great, but I would really like to use the bullet shortcut. It doesn't work.

® registered trademark is no problem, ² superscript is good, just to demonstrate that I know how to use Compose Key.

But alt.= for bullet yields nothing at all.

**Comment by tdierks** [comment]
This is probably because the bullet sign is missing from the version in the Chrome Webstore, which is v 1.4 from March 2017.

**Comment by bderrly** [comment]
I updated the extension to 1.7 a week or two ago. This new version has the bullet added.
