### ISSUE TITLE
Composing keys are also being output

### ISSUE THREAD

**Issue by janpfeifer** [google/extra-keyboards-for-chrome-os#34]
I just installed the extension through chrome-store, logged out and in again.

Now when I key in "alt-gr + ' + a", I get the sequence " 'áa ", that is single-quote + composed character + "a".

Any ideas what could be wrong ?
thanks!!

**Comment by ambalasis** [comment]
Same issue.
Platform: 10895.10.0 (Official Build) dev-channel setzer
Firmware: Google_Setzer.7287.381.0

**Comment by bderrly** [comment]
@janpfeifer I'm going to close this as I believe it was a bug introduced by Chrome OS that has since been fixed. If this is still an issue for you please open this issue again and I can take a closer look.
