### ISSUE TITLE
Compose key not working on ASUS C202S

### ISSUE THREAD

**Issue by 500mi** [google/extra-keyboards-for-chrome-os#40]
I am using an ASUS C202S with an English (US) keyboard. I have installed the ComposeKey extension, restarted my computer, and selected the `EN*` keyboard. However, I cannot type characters with the `Right Alt` key. Other keyboards, such as the `Pinyin input method`, work.

The keyboard is installed, enabled, and selected.

Has this been observed before by other users? I would appreciate any help with this!

**Comment by bderrly** [comment]
I haven't heard of any issues like this before. Have you tried removing it and installing it again? Have you tried it on a variety of input boxes on different sites/apps? Bear in mind the extension will not work on the login screen.
Lastly, which key combinations have you tried? A simple one to test is ° which is Right Alt followed by o and then o again.
