### ISSUE TITLE
ComposeKey not working (Chrome OS 70)

### ISSUE THREAD

**Issue by ambalasis** [google/extra-keyboards-for-chrome-os#42]
I was previously having another issue reported elsewhere where the component characters were being output as well as the composed character; with the latest update (Version 70.0.3538.41 (Official Build) beta (64-bit)), ComposeKey outputs nothing at all.

**Comment by bderrly** [comment]
@ambalasis has this been fixed in recent pushes of Chrome OS? I saw a few issues reported about this and I believe there was some change made to Chrome OS that broke this extension for a little while but has been fixed. Let me know if the problem persists and I can take a look at it.
