### ISSUE TITLE
Is it possible to input unicode characters with more than 4 characters?

### ISSUE THREAD

**Issue by nathgit** [google/extra-keyboards-for-chrome-os#43]
Is there a way to make it recognize something like U+1F512 (🔒)? It only gives me "ὑ2" meaning [U+1F51]+2. If it's not possible it's not a big deal, I'm just curious.

**Comment by bderrly** [comment]
It is possible to do this. First you should ensure you have at least version 1.7 of the extension. Open the extension options and add a custom sequence. For your example I created the following:

```
<Multi_key> <L> <O>: "\0x1F512"  # Unicode Lock
```

You can use any combination of keys you would like to trigger this. Try looking through [background.js](https://github.com/google/extra-keyboards-for-chrome-os/blob/master/composekey/background.js) for combinations that are already used.
