### ISSUE TITLE
Add support for Lushootseed input

### ISSUE THREAD

**Issue by bderrly** [google/extra-keyboards-for-chrome-os#45]
I received an email and a pull request (#41) from @dsienko to create an input method to allow entering characters usable with the Lushootseed language (a member of the Salish family of languages). Dave had issues with the pull request so I closed that in favor of tracking the creation of that here.

**Comment by bderrly** [comment]
I just published the extension to the Chrome Web Store at https://chrome.google.com/webstore/detail/lushootseed/bdcecklhaeiniooomgajkefmnghopnpk.

**Comment by dsienko** [comment]
Thank you so much!    It’s greatly appreciated!

Dave

Sent from my iPhone

On Apr 26, 2019, at 9:10 PM, Brian Derr <notifications@github.com<mailto:notifications@github.com>> wrote:


I just published the extension to the Chrome Web Store at https://chrome.google.com/webstore/detail/lushootseed/bdcecklhaeiniooomgajkefmnghopnpk.
