### ISSUE TITLE
ComposeKey extension can cause stuck keys

### ISSUE THREAD

**Issue by Narflex** [google/extra-keyboards-for-chrome-os#46]
For reference: crbug.com/840155

There's an issue when using Linux for Chromebooks when the ComposeKey extension is enabled. Linux for Chromebooks (also called Crostini) runs Linux applications on Chromebooks inside a VM/container. We use the wayland compositing server in Chrome and receive input events from it.  There's been reports from users that sometimes when they went into a Linux application that there would be keys repeating themselves, even though they weren't being pressed.

We did some more debugging of this, and then found a correlation to the ComposeKeys input method. It is required to be enabled in order for the bug to be reproduced; and given it's handling of keyboard events...this makes a lot of sense that it's the cause.  It's doing something where it ends up leaving keys in a pressed state sometimes, even though they are no longer being pressed. This doesn't manifest as a problem in Chrome or other apps AFAICT, and even within Linux only manifests itself with some X11 apps.

To reproduce the issue, do the following:

1. Setup Linux (Beta) on a Chromebook (it's in Settings)
2. Download VSCode or Sublime (these are 2 apps that can reproduce the issue pretty well) and install that into the Linux environment.
3. Run VSCode or Sublime and alt+tab back and forth (or switch focus with the mouse) and do various keyboard operations and sooner or later when you switch into the Linux app you will see a repeating key occurring. It's repeating because the list of pressed keys being maintained by the Chrome compositor has a stuck key in it.

**Comment by Narflex** [comment]
After receiving more feedback, I don't think this issue is with ComposeKeys; but with something else in the Chrome input stack. So I'll close it for now.

**Comment by gromgull** [comment]
There is a bug report (without much info) here: https://bugs.chromium.org/p/chromium/issues/detail?id=915248

I'd appreciate any pointers to where you think he problem is @Narflex!

**Comment by Narflex** [comment]
The problem wasn't in this extension...it was a bug in Chrome that I've since fixed. :)

**Comment by cameronj86** [comment]
I am encountering the exact same thing on my HP x360. It happens intermittently when tabbing between VS Code and another program. The 'tab' button gets stuck on repeat and floods my workspace.

**Comment by comjf** [comment]
I am still seeing this issue on my pixelbook (ChromeOS 78). Tab is stuck but only when alt-tabbing between Host (ChromeOS) to Crostini apps (not all, but at least Slack / Spotify / Atom). It does not happen when alt-tabbing between Crostini apps directly.

@Narflex You mention this isn't a problem with the extension, but rather with ChromeOS. Can you send me some links to the ChromeOS bug / previous fix so I can continue my troubleshooting? Thanks!

**Comment by Narflex** [comment]
Here's the fix I did: https://chromium-review.googlesource.com/c/chromium/src/+/1373010
