### ISSUE TITLE
Missing double arrow compositions

### ISSUE THREAD

**Issue by fastcat** [google/extra-keyboards-for-chrome-os#50]
In many other similar compose setups, the `special` + `=` + `<` or `>` produce the unicode `LEFTWARDS DOUBLE ARROW` `\u21d0` and `RIGHTWARDS DOUBLE ARROW` `\u21d2` characters.  It would be useful to have these available here, too.

**Comment by bderrly** [comment]
You have a few options to begin using these keys sooner than an extension update:
1.  Use the github repo as an unpacked extension
2.  Add a custom sequence in the options menu for the extension (assuming you've been updated to 1.7)

The XCompose sequence should look like this (add these after the 'include "%L"' line):
```
<Multi_key> <less> <equal>: "\0x21D0"  # LEFTWARDS DOUBLE ARROW
<Multi_key> <equal> <less>: "\0x21D0"  # LEFTWARDS DOUBLE ARROW
<Multi_key> <equal> <greater>: "\0x21D2"  # RIGHTWARDS DOUBLE ARROW
```
