### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by hickford** [google/extra-keyboards-for-chrome-os#53]
Looking at https://github.com/google/extra-keyboards-for-chrome-os/blob/master/gb-colemak/manifest.json I can't see where the keyboard layout is defined. I expected some data such as `qwfpgj`...

What have I missed?

**Comment by bderrly** [comment]
Some of the layouts in this repository simply make available layouts that are found in the xkeyboard-config package (https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/blob/master/symbols/gb in this case). Chrome OS does not expose every layout in the native picker so these extensions are made available to allow for the additional choice.

In the case of gb-colemak you find the `xkb_symbols "colemak"` section of the `symbols/gb` file. The layout will thus be named `gb(colemak)`.
