### ISSUE TITLE
More documentation / UK keyboard with swapped "/@

### ISSUE THREAD

**Issue by bjohas** [google/extra-keyboards-for-chrome-os#56]
Hello,

Would it be possible to post a link to documentation? 

I'd like to create a UK keyboard that has " and @ swapped. (There are basically two typed of UK keyboards, and they differ in a handful of keys, including " and @).

Using this approach, it would also seem possible to 'intercept' certain control/alt key combinations. Perhaps even search key combinations - but hard for me to figure out without documentation.

Is it possible to remap the 'top row' as well? Of course they can be turned into function keys, but then for some functions keys you would still want brightness up/down, so I wonder whether they have a keycode - thanks!

**Comment by bderrly** [comment]
There already exists a native UK layout with " and @ swapped (from the perspective of the American "qwerty" layout). In fact I'm using it to type this reply.

Open settings on your device, scroll to "Languages and input". Ensure that available languages include "English (United Kingdom)" (add it if it is not listed). Next expand the "Input method" and ensure that "UK keyboard" is selected. This is the basic UK layout (as described on wikipedia as "Windows keyboard": https://en.wikipedia.org/wiki/British_and_American_keyboards).

This set of extensions allows you to enable and use the "UK Extended" layout which provides additional options like letters with diacritical marks.

With regards to intercepting control and alt key combinations, what are you looking to accomplish?

With regards to the top row, there is an option in Chrome OS settings to flip the top row from "media" keys to "function" keys. Is that what you're after? Try searching for "function keys" in the settings window to find the option under "Keyboard"

**Comment by bjohas** [comment]
Hi @bderrly, thank you so much!

Your reply was really helpful - in an unexpected way. I have a physical UK keyboard on the Chromebook, with a UK keyboard layout. However, I'm actually used to the UK-Mac keyboard. The UK-Mac keyboard has the physical shape of the UK keyboard, but (as it turns out) with a layout that's essentially the US keyboard layout. So - I have switch my layout from UK to US, and now essentially have a UK-Mac keyboard. I hadn't thought of this before, and your post triggered this idea - thank you.

This fixes the keyboard layout for me, regarding the location of certain characters like @#:" - excellent.

Maybe to provide a rationale: I've come from OS X and am trying to explore chromeOS as an alternative. When I say from OS X, it's actually mainly using Chrome on OS X with Google Apps, plus very few other things. So I've enabled Linux support to get Linux equivalents of the few apps that I've previously used on Mac (e.g. Zotero). That's all good for far.

But - essentially what I am after is a keyboard layout that will ease the transition from Chrome on Mac to ChromeOS.

> With regards to the top row, there is an option in Chrome OS settings to flip the top row from "media" keys to "function" keys. Is that what you're after? Try searching for "function keys" in the settings window to find the option under "Keyboard"

Yes, thanks - I had found that setting.  What I'd like to do is to have about half the keys as special keys (e.g. keep full screen, keep the 'show windows' button, bright ness) but then use some of the other keys as hotkeys for other functions. For example, the Chromebook (HP x360 14) has physical volume buttons on the side. So I don't need the volume buttons on the keyboard, and would like to assign them to something else. For example, I'd quite like a button for 'next tab' and 'prev tab' (as I find the ctrl-tab combination awkward). Also, a dedicated key for voice input would be lovely.

This is to ease the transition: There are certain keyboard combinations that I am used to, but they don't have an equivalent. If I set up a dedicated key, then I can get used to this instead.

But, the following is more important, and what I would actually want to do:

> With regards to intercepting control and alt key combinations, what are you looking to accomplish?

I'd like to be able to intercept certain combinations so that they don't do anything (stopping random things happening when my muscle memory kicks in) or assign them as they were in OS X. As I've come from Chrome on Mac there's just a ton of things I have in my muscle memory, that slow me down considerable. Continuing with the theme of changing tabs above, I'm used to (effectively) altgr+shift+[ or ] on Chrome on OS X to change tabs.

So in an ideal world, 
(1) I would be able to intercept altgr+shift+[ and make that send a ctrl+shift+tab (and altgr+shift+] to send ctrl+tab). Then my muscle memory would just carry on.
(2) I would also like to get the search key to do a few more things. search+d for voice input is great, but I would like that on another key - and have 'beginning of line', 'end of line', 'forward delete', and 'kill', e.g. as search+a , search+e , search+d , search+k (essentially linux keybindings if you think of search as ctrl). That's so deeply embedded in muscle memory that it's really slowing me down. 

I know forward delete is alt-backspace, but I don't have that in muscle memory - is there a keyboard short cut for beginning of line / end of line? RightCtrl+leftarrow seems to work sometimes.

(3) I would also like to mess with the alt-tab vs. ctrl-tab shortcuts, making alt-tab send ctrl-tab and ctrl-tab send alt-tab.  

These three items would give me the perfect transition keyboard :) Any ideas what could be done?

Btw. you said you are using a UK keyboard at the moment - this might be of interest: When I switched from UK to US keyboard, it enabled a few hot keys in certain Google apps that weren't working before. E.g. ` in Gmail, as well as ctrl-alt-1234560 in google docs. For some reason those don't work with the UK keyboard, at least not on this model. Nothing to do with this extension, but keyboard related. Do those work for you, with the UK keyboard?

**Comment by bjohas** [comment]
It seems that the IME extensions require focus on an input field to be activated.

I managed to get alt-shift-[ to generate ctrl-tab, and thus alt-shift-[ can be used to change tabs. However, this only works if an input field is activated.

This makes all of the above impossible.

C.f. also https://www.chromium.org/developers/design-documents/extensions/proposed-changes/apis-under-development/input-method-editor

The Search key also seems to be intercepted at a lower level. 

I guess one way forward would be to put the whole Chromebook into developer mode, and then create lower level ways of handling the keyboard?

**Comment by bderrly** [comment]
Sorry for dropping this. You're right that this extension in particular only works on input fields inside a window managed by Chrome. To my knowledge (I don't work on the Chrome input team or hardware team), you cannot remap the Search key though maybe it is possible in dev mode (I've never looked).

I do not normally work on a UK keyboard. I was testing it out to when replying to you to see if it worked as expected. Unfortunately it seems that there is not a lot of customization possible with key remapping built into Chrome OS. It may be helpful for you that you can remap the Search key to Control or Escape or a few other options these days.

I am going to close this as there is not much this extension can do for you I think. I wish you well on your journey to keyboard layout nirvana. :)

**Comment by bjohas** [comment]
Many thanks for looking into it! All the best!
