### ISSUE TITLE
"Keep modifier" checkbox reset with computer startup

### ISSUE THREAD

**Issue by pr0t0m** [google/extra-keyboards-for-chrome-os#58]
I usually uncheck the "Keep modifier" box in options. But this setting is checked again when chromebook boots up.

**Comment by bderrly** [comment]
Can you check the console log for the extension to see if the values are being stored and synced properly. If you click on the extension settings and click on the "background page" link under "Inspect views". There may be some log messages there about storing or retrieving the values of the key to use and whether to set the keepModifier to true or false. My guess is that this is either not syncing properly and hence reverting to the default (which is true) or you have conflicting options between two devices or browsers that are fighting to store true or false.

**Comment by pr0t0m** [comment]
@bderrly Thanks for having a look.
`background.js:1252 Added 597 built-in sequences.`
`background.js:1411 Added 6 custom sequences.`
`background.js:1579 Loaded compose file from Chrome sync (397 characters).`
`background.js:1439 set key to Object [keepModifier: false ; key: "AltRight"]`
`background.js:1455 Stored key settings as Object [keepModifier: false ; key: "AltRight"]`
And when unchecking the box:
`background.js:1439 set key to Object [keepModifier: true ; key: "AltRight"]`
`background.js:1455 Stored key settings as Object [keepModifier: true ; key: "AltRight"]`
It looks likes sync goes wrong, and Chrome closing erases the stored value.
Please note that I have only one device, with only one browser.

**Comment by carnhofdaki** [comment]
> I usually uncheck the "Keep modifier" box in options. But this setting is checked again when chromebook boots up.

Yes, I noticed the same issue. CloudReady (Neverware Free)

**Comment by bderrly** [comment]
The issue is that the HTML has the box set to be checked by default rather than using the value that is stored in the synced settings. I'll have a change to fix it shortly.

**Comment by carnhofdaki** [comment]
@bderrly Thank you!
