### ISSUE TITLE
Compose Key not working in Crostini applications

### ISSUE THREAD

**Issue by Justin-Maxwell** [google/extra-keyboards-for-chrome-os#63]
compose-key is working for me in Chrome Apps, in the Crostini Terminal, but not in any of my windowed Linux apps.

I saw that compose-key is now available for UK keyboards.  Yay.   This is wonderful, because of course my workaround of using the Text Blaze Chrome extension (which is really good by the way), doesn't work for any Crostini keyboard entry.

So I installed the compose-key Google plugin, set it up for UK keyboard, saw it working in Terminal, thought everything was right with the world, only to find that it does nothing in half a dozen Linux apps I've tried.   

In an ideal world, both the compose-key and Text Blaze extensions would just work across all apps.
So I'm still stuck in the UX hell that is side-by-side-preview markdown editing for now I guess. 

Google Chrome | 77.0.3865.105 (Official Build) (64-bit)
Platform | 12371.75.3 (Official Build) stable-channel eve

**Comment by bderrly** [comment]
This extension is not a full input system that is used system-wide and thus will not work with Crostini. It only works on windows that are managed by Chrome and can run Javascript in the background.

Unfortunately the story for customizing the input system for Crostini has been stalled for a while. Feel free to star and follow the bug with ChromeOS input team: https://bugs.chromium.org/p/chromium/issues/detail?id=826614.
