### ISSUE TITLE
Feature request: Use search key as compose key.

### ISSUE THREAD

**Issue by Lattyware** [google/extra-keyboards-for-chrome-os#64]
On my desktop machines I use caps-lock as my compose key. As this translates in position to the search key, I would like to be able to use that as my compose key.

**Comment by bderrly** [comment]
Unfortunately we cannot override the Search or Launcher key with the extension. However, what you can do is override the value in Chrome OS settings (search in the settings menu for Keyboard) to behave as Alt and then set the extension to use AltLeft as the compose key.
