### ISSUE TITLE
Nepali keyboard

### ISSUE THREAD

**Issue by suniltheblue** [google/extra-keyboards-for-chrome-os#66]
Hello,

I wanted to create a modified version of existing Chrome OS keyboard for Nepali language to make it consistent with the one available in Windows. Many Keystrokes of the Chrome keyboard are different with the one available in Windows so, people familiar with the Windows input are not able to use the Chrome keyboard efficiently.

I would be grateful if I could get guidelines or tips to get stared. Thanks a lot.

Thanks a lot!

**Comment by bderrly** [comment]
You could take a look at what I did for the Lushootseed input here: https://github.com/google/extra-keyboards-for-chrome-os/blob/master/lushootseed/background.js

However, before doing that, some more information would be helpful. What sort of layout are you hoping to see? I just looked on my device and there are three different layouts for the Nepali language: (InScript, Phonetic, and transliteration). If you can use one of these for a base that would but much easier because then you could do something like what is done for the Slovak qwerty layout for example (https://github.com/google/extra-keyboards-for-chrome-os/blob/master/slovakqwerty/manifest.json).

**Comment by suniltheblue** [comment]
Thanks a lot for your kind help.

Yes, I could use the InScript layout as a base. Around 70% of the keys would be the same so I would have to change the rest of them only.

I checked the both of the examples you provided and I would be so thankful if you could help me about what I have to do change those 30% of the keys once I create the manifest.json file like the one of Slovak qwerty layout. Also, how to find the ID of the existing Nepali InScript keyboard to use as a base. Thanks again!

**Comment by bderrly** [comment]
Have you tried using the Google Input Tools yet? https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab for the Chrome extension and https://www.google.com/inputtools/ for general information. Are the Nepali layouts available there different than you are desiring?

**Comment by suniltheblue** [comment]
Yes, I've tried them and exactly that is what I wanted to modify. Leaving the phonetic and translietration keyboards apart (they are mostly used in mobile devices for short conversations) the most common keyboard for typing Nepali is the InScript keyboard (also called traditional keyboard). Unfortunately, Nepali keyboard layout in Windows and Chrome are not the same. Around 30% keys are placed differently, which creates great confusion and impacts the productivity of the people who are used to the Windows layout (and most of them are familiar with this one) to work on a Chrome/Chromium machine. I'm one of them, I love Chrome OS devices but can't use them at my work due to the different and weird placements of the keys. So, my intention is to create a layout called "Nepali Windowslike" to solve this problem.

**Comment by suniltheblue** [comment]
Hi, I've completed the code for the keyboard following your advice. Would you be able to take a look of it? Thanks a lot!

**Comment by bderrly** [comment]
Certainly, create a pull request and I can take a look. https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

**Comment by suniltheblue** [comment]
Thanks a lot. I've created it.

**Comment by bderrly** [comment]
@suniltheblue I closed the two pull requests you made due to inactivity. I'm going to close this as well. I hope you have found a useful option for input in the past year.
