### ISSUE TITLE
Android applications crash with Slovak QWERTY

### ISSUE THREAD

**Issue by matkoyy** [google/extra-keyboards-for-chrome-os#69]
Android applications hard crash when the Slovak QWERTY language keyboard layout, installed from this project, is currently set, and other than standard ASCII characters are inputted (diacritic characters, CTRL+SPACE, Tabulator etc.)
I think this started, when my Chromebook Acer R13 received Android 9 Pie version (from Chrome OS M78)
Chrome OS's Chrome browser is OK and works with no problem, only Android part is problematic.
Is this problem with this "keyboard extension", or is it some bug in Chrome OS?
Thank you
Martin

**Comment by empathicqubit** [comment]
I'm having a similar issue with Dvorak International. Changing to the keyboard will crash Android, and having it selected before any apps are launched will prevent it from starting.

**Comment by ludoja** [comment]
Same here, when Slovak qwerty enabled, play store and installed apps stop working, it is impossible to open them. When in app list, in app properties one does not see app info option.

**Comment by bderrly** [comment]
This has to be a problem somewhere in the layers between Chrome OS and Android. I am not familiar with how the subsystems handle keyboard inputs. I would recommend filing a bug in the [Chromium bug tracker](https://crbug.com/) about this.

**Comment by empathicqubit** [comment]
Hello everyone. Could you please star this issue and add any relevant information if you have it? Thanks! https://bugs.chromium.org/p/chromium/issues/detail?id=1173306
