### ISSUE TITLE
composekey bugs

### ISSUE THREAD

**Issue by broomdodger** [google/extra-keyboards-for-chrome-os#7]
acer c720 chromebook
chrome 38.0.2125.108
ComposeKey 1.1

`"^SM"` makes `ŜM` rather than `℠`
`"^SM": "\u2120", // SERVICE MARK`
Why not simply `"SM"`?

Both of these...
The leading `space` makes a `nobreakspace` followed by the second character.
`" .": "\u2008", // PUNCTUATION SPACE`
`" ,": "\u00b8", // cedilla # CEDILLA`

Question:
Why is trade mark more complicated than simply `"TM"`?
`"^TM": "\u2122", // TRADE MARK SIGN`

**Comment by bderrly** [comment]
@broomdodger, when would you ever use a cedilla by itself? You can do so by typing ", ", but why? I can't find any reference on the internets to using it without being attached to a 'c'.
