### ISSUE TITLE
URL "chrome://settings/inputMethods" didn't exists in chrome

### ISSUE THREAD

**Issue by sneyx123** [google/extra-keyboards-for-chrome-os#70]
It looks like "chrome://settings/inputMethods" didn't exists in chrome ... it immediate jumps (redirected) to "chrome://settings"

chome -- Version 79.0.3945.130

**Comment by bderrly** [comment]
Yes, the settings were change on Chrome OS sometime a while back I think in order to separate settings related to Chrome the browser and the OS. You should be able to find the input settings opening the settings app and then searching for "input" or "language" .

**Comment by bderrly** [comment]
Oops, I see that I need to update the README.md to reflect that. I'll do that in a bit.

**Comment by bderrly** [comment]
I fixed this in 09bcd3c645427a0185a164097169c4934ceddfcc.
