### ISSUE TITLE
ComposeKey "Keep modifier" settings is not remembered across sessions

### ISSUE THREAD

**Issue by attilaolah** [google/extra-keyboards-for-chrome-os#71]
The **Keep modifier** option for the ComposeKey extension seems to be forgotten after every reboot.

Poking a bit around in `background.js`, it might be due to the way it is set in `localStorage` and `chrome.storage.sync`. In `localStorage` we store it as so:

```js
  if (settings.keepModifier) {
    localStorage.setItem('keepModifier', "true");
  } else {
    localStorage.removeItem('keepModifier');
  }
```

And retrieve it as so:

```js
var keepModifier = localStorage.getItem('keepModifier') == "true";
```

…which seems correct. However, for Chrome Sync, we do this:

```js
  chrome.storage.sync.get({
    key: 'AltRight',
    // Default to keeping the modifier: otherwise, the default AltRight compose
    // key conflicts with AltGr in international layouts.
    keepModifier: true,
  }, (stored) => {
```

So here, if it is not set, we go with the default of `true`.

That said, it seems to be set properly in `options.js`, so I'm not sure what's going wrong here. But it is annoying to have to reset (disable) it every time.

**Comment by bderrly** [comment]
@attilaolah, maybe this was fixed already? See #58 where I disabled the default "checked" status on the input box. I haven't actually pushed a new version of the extension with that commit yet. Take a look at that issue and let me know if it's the same thing.

**Comment by attilaolah** [comment]
It looks like the same issue indeed. Do you plan to push a new version with that change, or should we pack & load this ourselves?

**Comment by attilaolah** [comment]
Re-opening this to ask for a new release. Can you push one to the Chrome Web Store plz?

**Comment by bderrly** [comment]
Yeah, I've been trying to get a new release pushed the last two weeks but I'm currently stuck in some review process rejection cycle. I hope to get it released this week. Sorry for the delay!

**Comment by attilaolah** [comment]
No worries! Let me know if I can help somehow.

**Comment by bderrly** [comment]
I pushed v1.8 Aug 7, 2020 which should have fixed this issue.

**Comment by attilaolah** [comment]
Yep it works now. Thanks!
