### ISSUE TITLE
korean phonetic keyboard?

### ISSUE THREAD

**Issue by nathgit** [google/extra-keyboards-for-chrome-os#73]
Is there anywhere to get a phonetic Korean keyboard? There's only one available & the mapping is nonsense. ㅎ is mapped to 'g' even though it's an 'h' sound & ㅗ is mapped to 'h' even though it's an 'o' sound. I also can't find the 'ㅇ' at all.

**Comment by bderrly** [comment]
I've been informed by some native Korean speakers that there is no good phonetic layout. Apparently the default Korean layout is the one that most everyone uses.
