### ISSUE TITLE
Custom keyboard layouts

### ISSUE THREAD

**Issue by limeb** [google/extra-keyboards-for-chrome-os#76]
I would like to add a keyboard layout not listed in the options.

Like a custom keyboard layout specifically.

    123456790-=
    ;,.pyfgcrl[]\
    aoeiudhtns'
    zqjkfbwv/

**Comment by nathgit** [comment]
I don't know if that's possible with this, but I would be interested to see someone who would no for sure comment. I posted an issue about getting a custom layout for korean, & haven't gotten any answers.

**Comment by bderrly** [comment]
Take a look at the Lushootseed keyboard https://github.com/google/extra-keyboards-for-chrome-os/blob/master/lushootseed/background.js. This is a remap of the QWERTY layout for a native language used in the Pacific northwest of the US.

**Comment by empathicqubit** [comment]
@limeb Not to judge, but you're going to give your brain a hard time if you make a Dvorak layout that only works on one system. It's easier to learn where the symbols usually are so you don't have to remember how to touch type two slightly different layouts, for the cases where your custom layout is impossible to setup.

**Comment by limeb** [comment]
@bderrly I don't understand why this was closed wouldn't it make sense to have a guide to add custom keyboard layouts to this extension or another?

**Comment by bderrly** [comment]
I actually have a set of documents drafted for how to add custom layouts. I
got distracted and forgot about it. I will try to get those completed and
pushed this week.
