### ISSUE TITLE
Dhivehi Phonetic keyboard for ChromeOS

### ISSUE THREAD

**Issue by RiyazMansoor** [google/extra-keyboards-for-chrome-os#77]
I am attaching the Dhivehi Phonetic keyboard v1. Uses Hebrew as the primary language (both Dhivehi and Hebrew is RTL)

Hopefully this make it into this repository :)
I have submitted my CLA as well.

[manifest.txt](https://github.com/google/extra-keyboards-for-chrome-os/files/4834266/manifest.txt)
[background.txt](https://github.com/google/extra-keyboards-for-chrome-os/files/4834267/background.txt)

**Comment by nathgit** [comment]
Here's the layout (using the QWERTY keyboard)
dhivehi/thaana layout (ތާނަ‎)
 \][ޕއޮއިއުޔތރއެއއް
'؛ލކޖހގފދސއަ
/.،މނބވޗ×ޒ
shift
|}{÷_ _ _ޠޓޜޭޢޤ÷
":ޅޚޛޙޣﷲޑށއާ
؟><ޟޏޞޥޝޘޡ

**Comment by nathgit** [comment]
\][ޕއޮއިއުއޔތރއެއއް
'؛ލކޖހގފދސއަ
/.،މނބވޗ×ޒ
shifted
|}{÷ޯީޫޠޓޜއޭޢޤ
؟><ޟޏޞޥޝޘޡ

**Comment by bderrly** [comment]
@RiyazMansoor I was about to suggest that you create your own repository for this keyboard layout and then I found that you already have a [Chrome extension](https://chrome.google.com/webstore/detail/thaana-phonetic-keyboard/lbkokgnilbbkpjnkeamgpbhmdojajngo?hl=iw) for it. Bravo!
