### ISSUE TITLE
[INFO] Souce of initial compose key values

### ISSUE THREAD

**Issue by anddam** [google/extra-keyboards-for-chrome-os#82]
I was looking into composing degree sign, I am curious about why the degree sign is associated to `oo` rather than `DG` and why copyright sign is associated to `oC`, as I would expect according to [this \(slightly old\) RFC](https://tools.ietf.org/rfc/rfc1345.txt).

Those sequences came from 2af867b, but what is their actual source?

Mentioning @KenjiBaheux as author.

**Comment by KenjiBaheux** [comment]
It was a while ago so I'm not sure anymore.
I *think* it was based on the documented sequences typically found on `*nix` systems.

**Comment by anddam** [comment]
> I think it was based on the documented sequences typically found on *nix systems.

I found the same definition in libX11, so I guess that answer my own question.

Closing this, thanks.
