### ISSUE TITLE
chrome://settings/inputMethod no longer exists

### ISSUE THREAD

**Issue by janpfeifer** [google/extra-keyboards-for-chrome-os#85]
There seems to be no such configuration as of 87.0.4280.47 (Official Build) beta (64-bit).

Any ideas how to enable it ?

**Comment by bderrly** [comment]
Yes, the input management has been moved to the Chrome OS settings which have been pulled apart from browser settings. https://support.google.com/chromebook/answer/1059492?hl=en this should help find the settings and how to toggle the layouts.

**Comment by djbclark** [comment]
At least in the released extension the doc in at least ComposeKey needs to be updated to reflect this, currently it still says:

Initial setup:
To enable the Compose key, open chrome://settings/inputMethods and select one of the Compose Key input methods.

Then, open chrome://settings/languages and enable the selected method. (You may need to sign out and back in first.)
