### ISSUE TITLE
Can't type after Shift + Alt Gr sequence

### ISSUE THREAD

**Issue by keithlee96** [google/extra-keyboards-for-chrome-os#86]
Repro steps on M86:

1. In Manage input methods, under language English, select 'UK Colemak'.
2. Switch to input method 'UK Colemak (EN)'.
3. Type normally. Verify you can type special characters such as á with Alt Gr+A.
4. Apply the sequence Shift (hold) + Alt Gr (hold) + (release shift) + (release Alt Gr)

See https://bugs.chromium.org/p/chromium/issues/detail?id=1149426.

**Comment by hickford** [comment]
I suspect the bug may be in upstream XKB. [gb(colemak)](https://github.com/freedesktop/xkeyboard-config/blob/77f114a12494c88fd8c9b144ec12f53e9677fedb/symbols/gb#L121) specifies ralt_switch_multikey whereas  [us(colemak)](https://github.com/freedesktop/xkeyboard-config/blob/77f114a12494c88fd8c9b144ec12f53e9677fedb/symbols/us#L796) (no bug) specifies ralt_switch

According to the XKB docs https://manpages.debian.org/testing/xkb-data/xkeyboard-config.7.en.html#Key_to_choose_the_3rd_level

> lv3:ralt_switch | Right Alt  
> lv3:ralt_switch_multikey | Right Alt; Shift+Right Alt as Compose

Compose key isn't appropriate for Colemak, which uses Right Alt as a dead key https://colemak.com/Multilingual. This explains the bug

**Comment by hickford** [comment]
Reported upstream in XKB https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/237

**Comment by hickford** [comment]
[Fixed in upstream xkeyboard-config-2.32](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commits/xkeyboard-config-2.32?utf8=%E2%9C%93&search=gb%28colemak%29)

It remains to update xkeyboard-config in Chrome OS https://crbug.com/1149426

**Comment by 7fe** [comment]
@keithlee96 can this be closed now?
